### ISSUE TITLE
mergeLayers function

### ISSUE THREAD

**Issue by AlarconRios** [hiweller/recolorize#4]
Dear Hannah, 
First, I would like to say thank you for this fantastic package. It is resulting extremly useful for my color analysis, and I am saving a lot of time!. 

I would like to ask a question about the output of the 'mergeLayers' function. 

I have an 'imposeColors()' object that includes several images segmented in 7 colors. Now I would like to merge two of the colors because one is actually a light reflection artifact of the second one. I used the following code: 

mlist <- list(c(1,5),2,3,4,6,7)
impose_list_merged <- lapply(impose_list, 
                             function(i) mergeLayers(i, merge_list = mlist,
                                                    plotting=T))

If I keep 'plotting=T' it doesn't work and return the following warning message: 

Error in rgb(t(x[, , 1L]), t(x[, , 2L]), t(x[, , 3L]), t(x[, , 4L]), maxColorValue = max) :
color intensity 6, not in [0,1]

Conversely, If I set plotting=FALSE, the function runs and generates the 'impose_list_merged' object, although  I can not plot segmented images from it because a similar error. 

Inspecting different generated objects, I realized that in the 'mergeLayers()' object (impose_list_merged), some of the images has less colors than they were supposed to after merging (i.e. less than 6 colors). Conversely, in the 'imposeColors()' object (impose_list) all of them have 7 colors. 

The only explanation that I found is that color 6 does not appear in all images. Indeed I noticed that for those images in which color 6 size is 0 it is dropped after merging, and thus, those images had less than 6 colors in the 'mergeLayers()' output. I would like to point out that I used this function previously in other dataset and that it perfectly worked, although in those images all colors appeared in all images. 

Although I can merge different layers sizes manually using a table and summing each color column, I would like to ask if there is any way to merge layers to generate plots.
 
Please, let me know whether I provided enough information to solve this issue.

Thank you in advance, 
Best regards,

Lucía

**Comment by hiweller** [comment]
Hi Lucía,

First, I'm so glad you're finding the package useful! And second: thank you for posting this issue to the GitHub; I think you found a bug!

## Explanation

In the old [mergeLayers](https://github.com/hiweller/recolorize/commit/38d4ac7d3ca0c0c745fb96ac98cf4a38c7ed5289?diff=split#diff-77445ac2ee908e4716e8e9dc17b46695e7585c70d2f102d6bd87afd1a1d34dca) function, it deleted any layers specified in the merge_list argument that ended up having a size of 0 (lines 179-182):

```
if (any(new_sizes == 0)) {
    new_centers <- new_centers[-which(new_sizes == 0), ]
    new_sizes <- new_sizes[-which(new_sizes == 0)]
  }
```

Two problems here...

1) The function doesn't give you an option to not delete these empty color centers if you want to keep them (which is sometimes needed for batch processing). 

2) It doesn't reassign the numbers in the pixel assignments. So for example, if color 6 has a size of 0, the code as it is written will delete the 6th row of the color centers matrix and the 6th element of the color sizes vector, making the 7th color center the 6th one in these two elements. But the pixel assignment matrix (the 'paint-by-numbers' matrix that tells recolorize which color center each pixel is assigned to) would have pixels assigned to color classes 1, 2, 3, 4, 5, and **7**, not 6, because I didn't write code to reassign those values. 

Trying to plot the resulting matrix results in an error, because the function does not provide a color center for pixels labeled as '7', so the plotting function tries to use 7 as the color value. But because the plot.recolorize function assumes that all the RGB triplets are in a 0-1 range (which they're supposed to be), it throws an error that 7 is greater than 1 and the function doesn't know what color to plot.

## Solution

I have [updated the development version of the package](https://github.com/hiweller/recolorize/blob/master/R/mergeLayers.R) so that that section of the mergeLayers function correctly re-indexes the pixel assignments, and added a `remove_empty_centers` argument to the function so that users can choose whether to drop empty color centers or keep them for batch processing consistency.

## Example

```
# reinstall the package:
devtools::install_github("hiweller/recolorize")
library(recolorize)

# fit a recolorize object with 8 clusters:
img <- system.file("extdata/corbetti.png", package = "recolorize")
rc <- recolorize2(img, bins = 2)

# artificially delete cluster 6 from one of the images to recreate the problem:
rc$pixel_assignments[rc$pixel_assignments == 5] <- 3
rc$sizes[3] <- rc$sizes[5] + rc$sizes[3]
rc$sizes[5] <- 0

# verify that cluster 5 is now a size of 0:
rc$centers
rc$sizes
table(rc$pixel_assignments)
plot(rc) # notice that the pink cluster (5) is gone now

# merge colors 4 and 7, keeping the (empty) cluster 5, which becomes color 4:
rc_merge <- mergeLayers(rc, list(c(4, 7)), plotting = T)

# alternatively, drop it because it has a size of 0:
rc_merge <- mergeLayers(rc, list(c(4, 7)), remove_empty_centers = TRUE, plotting = T)
```
